### ISSUE TITLE
Blurred menu text.

### ISSUE THREAD

**Issue by BreadMaker** [rmcauley/rainwave#113]
In Iceweasel (Debian rebrand of Firefox) v38.5.0, everything is perfect, no blur at all.

But in Chromium (open-source version of Chrome) v47.0.2526.80, there is some kind of "blur" in the menu, like the text is aligned at the mid-pixel of the line. I also noticed the same issue with the menu icon.

(click to view them pixel-perfect)

Iceweasel
![firefox](https://cloud.githubusercontent.com/assets/713711/12458736/12bf1920-bf8a-11e5-9fc6-5837837a81d1.png)

Chromium
![chrome](https://cloud.githubusercontent.com/assets/713711/12458740/1696c502-bf8a-11e5-91fb-147f72913664.png)

**Comment by rmcauley** [comment]
It's because we are forced to use 3D transitions on the transforms, otherwise the entire menu flashes orange in a completely hideous manner because of a Safari bug.  Chrome is collateral damage.

See http://rainwave.cc/forums/viewtopic.php?f=17&t=5242

**Comment by BreadMaker** [comment]
Oh, bummer.
