### ISSUE TITLE
"Song already requested" > "Your queue is full"

### ISSUE THREAD

**Issue by villermen** [rmcauley/rainwave#135]
Very minor change. I think it's more informative to show an error that a song is already in your queue when it also cannot be added due to your queue being full. Removing another song will lead to a second error right now, but it is the remaining condition.

**Comment by rmcauley** [comment]
:+1: thanks for the feedback!  Let me know if there's anything else. :)  That "removing another song" sounds interesting. 💭

**Comment by villermen** [comment]
What I *meant* to say was:

1. Queue a song that is already queued, and the queue is full -> "Your queue is full"
2. Removing another song *from the queue* and trying to add it again -> "Song already requested"

The second part was just poorly phrased =S.

Thanks for the quick fix!

**Comment by rmcauley** [comment]
Ah, I see what you mean!

And yeah, it's a small fix, so it was easy to make! :)  When it'll hit the site is another matter, but considering the nature of the bug I'm not going to go out of my way to deploy it right now. :)

**Comment by rmcauley** [comment]
Deployed!
