### ISSUE TITLE
Album art scan matches too many folders

### ISSUE THREAD

**Issue by williamjacksn** [rmcauley/rainwave#152]
https://github.com/rmcauley/rainwave/blob/58f30ffa785229fc4357066e9c9a2fc12b0ba143/backend/filemonitor.py#L268

When scanning album art and looking for album IDs to apply the art to, you probably should append a path separator to the results of the `dirname()` call before searching in the database.

For example:

1. Scanner found a new art file at `/home/icecast/ocr-all/FinalFantasyIX/FinalFantasyIX.jpg`
2. Scanner searched the database for songs `WHERE song_filename LIKE '/home/icecast/ocr-all/FinalFantasyIX%'`
3. This incorrectly included songs in the directory `/home/icecast/ocr-all/FinalFantasyIXWorldsApart`

**Comment by rmcauley** [comment]
Well flippin' spotted my good man!

**Comment by williamjacksn** [comment]
Here is where it was introduced:

https://github.com/rmcauley/rainwave/commit/cb45e1f5efc01a54b697c969aedfe7d31d18e85f#diff-a851b58349e59ff54bad15e7399f64da

**Comment by rmcauley** [comment]
Fix has been deployed.
