### ISSUE TITLE
Content Security Policy Error

### ISSUE THREAD

**Issue by jonathanscleon** [rmcauley/rainwave#155]
Hi, I'm getting a Content Security Policy Error when using Rainwave with Firefox.

The error reads "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”)" for the following files:
 pagewrap.bundle.js:1:1151
 utils.js:35:9

If you get time to take a look, I'd really appreciate it.

**Comment by rmcauley** [comment]
Hi Jonathan, we do not have a `utils.js` or a `pagewrap.bundle.js`.  This is most likely an extension.  Can you try Firefox in safe mode?

**Comment by jonathanscleon** [comment]
Ah, I see. Hm, after I ran it in a private window it now works in the regular window too. Thanks for responding so quickly, and apologies for bothering you with a non-issue.

I really appreciate the work you put into this! It really helps me get through my work day.
