### ISSUE TITLE
Rainwave 4 doesn't look so great on vertical displays

### ISSUE THREAD

**Issue by applmak** [rmcauley/rainwave#41]
In particular, the columns are too narrow to display the text they're supposed to display. Would you add a tall-screen mode that fixes this?

**Comment by rmcauley** [comment]
I'm developing a new version of Rainwave on the R5 branch, and will be making much better use of varying screen sizes.  I will be sticking with the column-based layout, but screens between 1050px and 1365px will be a bit cramped and will have things like album art removed.  1050px should be enough to accommodate users who use 1080p monitors vertically aligned.  Any narrower, and you'll get stuck with the single-column interface for tablets and phones.
