### ISSUE TITLE
instructions for testing/dev do not work

### ISSUE THREAD

**Issue by eyecreate** [rmcauley/rainwave#74]
I follwed the instructions for frontend dev on a fresh ubuntu machine and got complaints about the DB. A repeatable testing env will help make running easier. A nice solution could be Vagrant.

**Comment by BreadMaker** [comment]
Another one to consider could be [Docker](https://www.docker.com/).

**Comment by rmcauley** [comment]
Ack, sorry about that.  The main problem is as soon as we make a database schema change I need to update the sample DB that's in the Git repository.  I'll post a fresh version and follow the instructions from scratch as you would, and try again.  (I'm booked solid the next few days, though, so it might be a bit of a wait, sorry :( )

**Comment by williamjacksn** [comment]
I have a Vagrantfile that I use for this personally. I can make sure it is still in working order and commit it if there is interest.

**Comment by BreadMaker** [comment]
:+1:  to that, @williamjacksn

**Comment by rmcauley** [comment]
Keep in mind that the Vagrant file will require you (I think) to have a Postgres server at the ready, and will use your own collection of MP3s.  This is different from the easy/sample startup, which if I was more diligent in keeping up to date, wouldn't require either.  :/

**Comment by williamjacksn** [comment]
The Vagrantfile will set up the Postgres server in the virtual machine. You do need your own mp3 files, though. See https://github.com/rmcauley/rainwave/blob/master/etc/README_DEV.md

**Comment by williamjacksn** [comment]
Also I wrote the Vagrantfile with an eye to back-end and API development, not front-end development. So it needs some work.

**Comment by rmcauley** [comment]
I've reconstructed the sample DB file and tested it locally, it ought to work now if anyone wants to just develop against the front-end.  Keep in mind not all functions may work, specifically the more DB-intensive functions such as requesting favourites or requested unrated songs.
